/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\public\models\Tablet.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Tablet(props) {
  const { nodes, materials } = useGLTF('/models/Tablet.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.LP1_uv_checker_material_uv_grid_4096x4096_0_1.geometry} material={materials['01___Default']} />
      <mesh geometry={nodes.LP1_uv_checker_material_uv_grid_4096x4096_0_2.geometry} material={materials['02___Default']} />
      <mesh geometry={nodes.LP1_uv_checker_material_uv_grid_4096x4096_0_3.geometry} material={materials['04___Default']} />
      <mesh geometry={nodes.LP2_uv_checker_material_uv_grid_4096x4096_0.geometry} material={materials['03___Default']} />
    </group>
  )
}

useGLTF.preload('/Tablet.glb')
